//! Removes liquidity from a Uniswap V2-compatible pair using interfaces generated by `sol!`.
//!
//! Configure `RPC_URL`, `PRIVATE_KEY`, `PAIR_ADDRESS`, `ROUTER_ADDRESS`, `LIQUIDITY_AMOUNT`,
//! `MIN_AMOUNT_0`, and `MIN_AMOUNT_1` before running. Amounts use each token's raw units. Test the
//! parameters on a local fork first: this example signs an approval and a removal transaction.

use std::time::{SystemTime, UNIX_EPOCH};

use alloy::{
    primitives::{Address, U256},
    providers::ProviderBuilder,
    signers::local::PrivateKeySigner,
    sol,
};
use example_support::{required_env, rpc_url};
use eyre::{ensure, Result, WrapErr};

const DEADLINE_SECONDS: u64 = 20 * 60;

sol! {
    #[allow(missing_docs)]
    #[sol(rpc)]
    interface IUniswapV2Factory {
        function getPair(address tokenA, address tokenB) external view returns (address pair);
    }

    #[allow(missing_docs)]
    #[sol(rpc)]
    interface IUniswapV2Pair {
        function approve(address spender, uint256 value) external returns (bool);
        function balanceOf(address owner) external view returns (uint256);
        function getReserves()
            external
            view
            returns (uint112 reserve0, uint112 reserve1, uint32 blockTimestampLast);
        function token0() external view returns (address);
        function token1() external view returns (address);
    }

    #[allow(missing_docs, clippy::too_many_arguments)]
    #[sol(rpc)]
    interface IUniswapV2Router02 {
        function factory() external view returns (address);

        function removeLiquidity(
            address tokenA,
            address tokenB,
            uint256 liquidity,
            uint256 amountAMin,
            uint256 amountBMin,
            address to,
            uint256 deadline
        ) external returns (uint256 amountA, uint256 amountB);
    }
}

fn parse_value<T>(name: &str, value: String) -> Result<T>
where
    T: std::str::FromStr,
    T::Err: std::error::Error + Send + Sync + 'static,
{
    value.parse().wrap_err_with(|| format!("invalid {name}"))
}

#[tokio::main]
async fn main() -> Result<()> {
    // Keep credentials and deployment-specific values outside the source code.
    let signer: PrivateKeySigner = parse_value("PRIVATE_KEY", required_env("PRIVATE_KEY")?)?;
    let owner = signer.address();
    let pair_address: Address = parse_value("PAIR_ADDRESS", required_env("PAIR_ADDRESS")?)?;
    let router_address: Address = parse_value("ROUTER_ADDRESS", required_env("ROUTER_ADDRESS")?)?;
    let liquidity: U256 = parse_value("LIQUIDITY_AMOUNT", required_env("LIQUIDITY_AMOUNT")?)?;
    let amount_0_min: U256 = parse_value("MIN_AMOUNT_0", required_env("MIN_AMOUNT_0")?)?;
    let amount_1_min: U256 = parse_value("MIN_AMOUNT_1", required_env("MIN_AMOUNT_1")?)?;
    ensure!(!liquidity.is_zero(), "LIQUIDITY_AMOUNT must be greater than zero");

    let provider = ProviderBuilder::new().wallet(signer).connect_http(rpc_url()?.parse()?);
    let pair = IUniswapV2Pair::new(pair_address, &provider);
    let router = IUniswapV2Router02::new(router_address, &provider);

    let lp_balance = pair.balanceOf(owner).call().await?;
    ensure!(
        lp_balance >= liquidity,
        "wallet has {lp_balance} LP tokens, but LIQUIDITY_AMOUNT is {liquidity}"
    );

    let token_0_call = pair.token0();
    let token_1_call = pair.token1();
    let reserves_call = pair.getReserves();
    let factory_call = router.factory();
    let (token_0, token_1, reserves, factory_address) = tokio::try_join!(
        token_0_call.call(),
        token_1_call.call(),
        reserves_call.call(),
        factory_call.call(),
    )?;

    let factory = IUniswapV2Factory::new(factory_address, &provider);
    let router_pair = factory.getPair(token_0, token_1).call().await?;
    ensure!(
        router_pair == pair_address,
        "PAIR_ADDRESS {pair_address} does not match router pair {router_pair}"
    );

    println!(
        "Removing {liquidity} LP tokens from {pair_address}\n\
         token0: {token_0} (reserve: {})\n\
         token1: {token_1} (reserve: {})",
        reserves.reserve0, reserves.reserve1
    );

    let approval_receipt =
        pair.approve(router_address, liquidity).send().await?.get_receipt().await?;
    ensure!(approval_receipt.status(), "LP token approval transaction reverted");
    println!("Approved router in transaction {}", approval_receipt.transaction_hash);

    let deadline = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .wrap_err("system clock is before the Unix epoch")?
        .as_secs()
        .checked_add(DEADLINE_SECONDS)
        .ok_or_else(|| eyre::eyre!("deadline overflow"))?;

    // Simulate first so invalid minimum amounts fail before signing the removal transaction.
    let quoted = router
        .removeLiquidity(
            token_0,
            token_1,
            liquidity,
            amount_0_min,
            amount_1_min,
            owner,
            U256::from(deadline),
        )
        .call()
        .await?;
    println!("Simulation: token0 out {}, token1 out {}", quoted.amountA, quoted.amountB);

    let receipt = router
        .removeLiquidity(
            token_0,
            token_1,
            liquidity,
            amount_0_min,
            amount_1_min,
            owner,
            U256::from(deadline),
        )
        .send()
        .await?
        .get_receipt()
        .await?;
    ensure!(receipt.status(), "remove-liquidity transaction reverted");

    println!("Removed liquidity in transaction {}", receipt.transaction_hash);
    Ok(())
}
