# Runs weeky `cargo update` to keep dependencies current.

name: Dependencies

on:
  schedule:
    # Run weekly
    - cron: "0 0 * * SUN"
  workflow_dispatch:
    # Needed so we can run it manually

env:
  BRANCH: cargo-update
  TITLE: "chore(deps): weekly `cargo update`"
  BODY: |
    Automation to keep dependencies in `Cargo.lock` current.

    <details><summary><strong>cargo update log</strong></summary>
    <p>

    ```log
    $cargo_update_log
    ```

    </p>
    </details>

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@117919c943b804057be733b0c4034c5542e58959 # 2026-09-23T05-09-41Z-117919c9
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@02cb101ec7c40f2c49e1d9714d64511d8e1b74de # v1
        with:
          toolchain: nightly

      - name: cargo update
        # Remove first line that always just says "Updating crates.io index"
        run: cargo update --color never 2>&1 | sed '/crates.io index/d' | tee -a cargo_update.log

      - name: Check updated dependencies
        run: cargo check --workspace --examples --all-features --locked

      - name: craft commit message and PR body
        id: msg
        run: |
          cargo_update_log="$(cat cargo_update.log)"
          export cargo_update_log

          {
            echo "commit_message<<EOF"
            printf '%s\n\n%s\n' "$TITLE" "$cargo_update_log"
            echo "EOF"
            echo "body<<EOF"
            printf '%s\n' "$BODY" | envsubst
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          add-paths: ./Cargo.lock
          commit-message: ${{ steps.msg.outputs.commit_message }}
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: ${{ env.TITLE }}
          body: ${{ steps.msg.outputs.body }}
          branch: ${{ env.BRANCH }}
